# Generated by Django 5.2.3 on 2025-06-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_prize', models.IntegerField(default=0, null=True)),
                ('stock_value', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
