# Generated by Django 5.2.3 on 2025-06-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_category_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_prize',
            new_name='product_price',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(null=True, upload_to='product_images/'),
        ),
    ]
