# Generated by Django 5.2.3 on 2025-06-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_order_ordered_at_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Placed', max_length=20),
        ),
    ]
