# Generated by Django 5.2.3 on 2025-06-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_review_product_alter_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='feedback_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
