# Generated by Django 5.2.3 on 2025-06-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_order_feedback_time_delete_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='feedback_time',
            new_name='feedback_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
